/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSuitesRouteImport } from './routes/_authed/suites'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedRunsRouteImport } from './routes/_authed/runs'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedSuitesIndexRouteImport } from './routes/_authed/suites/index'
import { Route as AuthedRunsIndexRouteImport } from './routes/_authed/runs/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedSuitesNewRouteImport } from './routes/_authed/suites/new'
import { Route as AuthedSuitesSuiteIdRouteImport } from './routes/_authed/suites/$suiteId'
import { Route as AuthedRunsRunIdRouteImport } from './routes/_authed/runs/$runId'
import { Route as ApiV1RunsIndexRouteImport } from './routes/api/v1/runs/index'
import { Route as ApiV1RunsRunIdRouteImport } from './routes/api/v1/runs/$runId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSuitesRoute = AuthedSuitesRouteImport.update({
  id: '/suites',
  path: '/suites',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRunsRoute = AuthedRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSuitesIndexRoute = AuthedSuitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSuitesRoute,
} as any)
const AuthedRunsIndexRoute = AuthedRunsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRunsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSuitesNewRoute = AuthedSuitesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedSuitesRoute,
} as any)
const AuthedSuitesSuiteIdRoute = AuthedSuitesSuiteIdRouteImport.update({
  id: '/$suiteId',
  path: '/$suiteId',
  getParentRoute: () => AuthedSuitesRoute,
} as any)
const AuthedRunsRunIdRoute = AuthedRunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => AuthedRunsRoute,
} as any)
const ApiV1RunsIndexRoute = ApiV1RunsIndexRouteImport.update({
  id: '/api/v1/runs/',
  path: '/api/v1/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RunsRunIdRoute = ApiV1RunsRunIdRouteImport.update({
  id: '/api/v1/runs/$runId',
  path: '/api/v1/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/runs': typeof AuthedRunsRouteWithChildren
  '/settings': typeof AuthedSettingsRoute
  '/suites': typeof AuthedSuitesRouteWithChildren
  '/runs/$runId': typeof AuthedRunsRunIdRoute
  '/suites/$suiteId': typeof AuthedSuitesSuiteIdRoute
  '/suites/new': typeof AuthedSuitesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/runs/': typeof AuthedRunsIndexRoute
  '/suites/': typeof AuthedSuitesIndexRoute
  '/api/v1/runs/$runId': typeof ApiV1RunsRunIdRoute
  '/api/v1/runs/': typeof ApiV1RunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/settings': typeof AuthedSettingsRoute
  '/runs/$runId': typeof AuthedRunsRunIdRoute
  '/suites/$suiteId': typeof AuthedSuitesSuiteIdRoute
  '/suites/new': typeof AuthedSuitesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/runs': typeof AuthedRunsIndexRoute
  '/suites': typeof AuthedSuitesIndexRoute
  '/api/v1/runs/$runId': typeof ApiV1RunsRunIdRoute
  '/api/v1/runs': typeof ApiV1RunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/runs': typeof AuthedRunsRouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/suites': typeof AuthedSuitesRouteWithChildren
  '/_authed/runs/$runId': typeof AuthedRunsRunIdRoute
  '/_authed/suites/$suiteId': typeof AuthedSuitesSuiteIdRoute
  '/_authed/suites/new': typeof AuthedSuitesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/runs/': typeof AuthedRunsIndexRoute
  '/_authed/suites/': typeof AuthedSuitesIndexRoute
  '/api/v1/runs/$runId': typeof ApiV1RunsRunIdRoute
  '/api/v1/runs/': typeof ApiV1RunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/runs'
    | '/settings'
    | '/suites'
    | '/runs/$runId'
    | '/suites/$suiteId'
    | '/suites/new'
    | '/api/auth/$'
    | '/runs/'
    | '/suites/'
    | '/api/v1/runs/$runId'
    | '/api/v1/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/settings'
    | '/runs/$runId'
    | '/suites/$suiteId'
    | '/suites/new'
    | '/api/auth/$'
    | '/runs'
    | '/suites'
    | '/api/v1/runs/$runId'
    | '/api/v1/runs'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/dashboard'
    | '/_authed/runs'
    | '/_authed/settings'
    | '/_authed/suites'
    | '/_authed/runs/$runId'
    | '/_authed/suites/$suiteId'
    | '/_authed/suites/new'
    | '/api/auth/$'
    | '/_authed/runs/'
    | '/_authed/suites/'
    | '/api/v1/runs/$runId'
    | '/api/v1/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1RunsRunIdRoute: typeof ApiV1RunsRunIdRoute
  ApiV1RunsIndexRoute: typeof ApiV1RunsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/suites': {
      id: '/_authed/suites'
      path: '/suites'
      fullPath: '/suites'
      preLoaderRoute: typeof AuthedSuitesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/runs': {
      id: '/_authed/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof AuthedRunsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/suites/': {
      id: '/_authed/suites/'
      path: '/'
      fullPath: '/suites/'
      preLoaderRoute: typeof AuthedSuitesIndexRouteImport
      parentRoute: typeof AuthedSuitesRoute
    }
    '/_authed/runs/': {
      id: '/_authed/runs/'
      path: '/'
      fullPath: '/runs/'
      preLoaderRoute: typeof AuthedRunsIndexRouteImport
      parentRoute: typeof AuthedRunsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/suites/new': {
      id: '/_authed/suites/new'
      path: '/new'
      fullPath: '/suites/new'
      preLoaderRoute: typeof AuthedSuitesNewRouteImport
      parentRoute: typeof AuthedSuitesRoute
    }
    '/_authed/suites/$suiteId': {
      id: '/_authed/suites/$suiteId'
      path: '/$suiteId'
      fullPath: '/suites/$suiteId'
      preLoaderRoute: typeof AuthedSuitesSuiteIdRouteImport
      parentRoute: typeof AuthedSuitesRoute
    }
    '/_authed/runs/$runId': {
      id: '/_authed/runs/$runId'
      path: '/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof AuthedRunsRunIdRouteImport
      parentRoute: typeof AuthedRunsRoute
    }
    '/api/v1/runs/': {
      id: '/api/v1/runs/'
      path: '/api/v1/runs'
      fullPath: '/api/v1/runs/'
      preLoaderRoute: typeof ApiV1RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/runs/$runId': {
      id: '/api/v1/runs/$runId'
      path: '/api/v1/runs/$runId'
      fullPath: '/api/v1/runs/$runId'
      preLoaderRoute: typeof ApiV1RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRunsRouteChildren {
  AuthedRunsRunIdRoute: typeof AuthedRunsRunIdRoute
  AuthedRunsIndexRoute: typeof AuthedRunsIndexRoute
}

const AuthedRunsRouteChildren: AuthedRunsRouteChildren = {
  AuthedRunsRunIdRoute: AuthedRunsRunIdRoute,
  AuthedRunsIndexRoute: AuthedRunsIndexRoute,
}

const AuthedRunsRouteWithChildren = AuthedRunsRoute._addFileChildren(
  AuthedRunsRouteChildren,
)

interface AuthedSuitesRouteChildren {
  AuthedSuitesSuiteIdRoute: typeof AuthedSuitesSuiteIdRoute
  AuthedSuitesNewRoute: typeof AuthedSuitesNewRoute
  AuthedSuitesIndexRoute: typeof AuthedSuitesIndexRoute
}

const AuthedSuitesRouteChildren: AuthedSuitesRouteChildren = {
  AuthedSuitesSuiteIdRoute: AuthedSuitesSuiteIdRoute,
  AuthedSuitesNewRoute: AuthedSuitesNewRoute,
  AuthedSuitesIndexRoute: AuthedSuitesIndexRoute,
}

const AuthedSuitesRouteWithChildren = AuthedSuitesRoute._addFileChildren(
  AuthedSuitesRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedRunsRoute: typeof AuthedRunsRouteWithChildren
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedSuitesRoute: typeof AuthedSuitesRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedRunsRoute: AuthedRunsRouteWithChildren,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedSuitesRoute: AuthedSuitesRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1RunsRunIdRoute: ApiV1RunsRunIdRoute,
  ApiV1RunsIndexRoute: ApiV1RunsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
