import type { Database } from '@validater/db';
import { testSuites, testCases } from '@validater/db';
import type { TestStep } from '@validater/core';
import { nanoid } from 'nanoid';
import { eq } from 'drizzle-orm';

export interface PersistSuiteParams {
  suiteId: string;
  testCases: Array<{
    name: string;
    description: string;
    category: 'happy_path' | 'edge_case' | 'error_state' | 'boundary';
    priority: 'critical' | 'high' | 'medium' | 'low';
    reasoning: string;
    steps: TestStep[];  // Steps generated by existing pipeline
    index: number;
  }>;
}

/**
 * Factory function for suite persistence activities.
 * Uses dependency injection -- db client injected at worker setup.
 * Same pattern as createPersistActivities.
 */
export function createPersistSuiteActivities(db: Database) {
  /**
   * Persist generated suite test cases (with their steps) to the database.
   * Updates the suite status to 'complete' and sets testCaseCount.
   */
  async function persistSuite(params: PersistSuiteParams): Promise<void> {
    for (const tc of params.testCases) {
      await db.insert(testCases).values({
        id: nanoid(),
        suiteId: params.suiteId,
        name: tc.name,
        description: tc.description,
        category: tc.category,
        priority: tc.priority,
        reasoning: tc.reasoning,
        steps: tc.steps,
        order: tc.index + 1,
      });
    }

    // Update suite status to complete with test case count
    await db
      .update(testSuites)
      .set({
        status: 'complete',
        testCaseCount: params.testCases.length,
        updatedAt: new Date(),
      })
      .where(eq(testSuites.id, params.suiteId));
  }

  /**
   * Update suite status (for progress tracking).
   */
  async function updateSuiteStatus(params: {
    suiteId: string;
    status: string;
    error?: string;
  }): Promise<void> {
    await db
      .update(testSuites)
      .set({ status: params.status, updatedAt: new Date() })
      .where(eq(testSuites.id, params.suiteId));
  }

  return { persistSuite, updateSuiteStatus };
}

export type PersistSuiteActivities = ReturnType<typeof createPersistSuiteActivities>;
